### ISSUE TITLE
High severity vulnerability in dependency async

### ISSUE THREAD

**Issue by daves-weblab** [DevExpress/testcafe-legacy-api#59]
This package depends on async in version 0.2.6. There was a high severity vulnerability found in async versions lower than 3.2.2 https://github.com/advisories/GHSA-fwr7-v2mv-hh25

Is it possible to update this dependency?

**Comment by kirovboris** [comment]
Hello @daves-weblab, 
Thank you for your report!
We'll release fix in the next minor version of `testcafe`.
